
#Https configuration
#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-password: liberbee
#    key-store-type: JKS
#    key-alias: liberbee
#    key-store-password: liberbee
#  port: 8000

#Data Source
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.100/companies
    username: postgres
    password: rge4;21ZLA
    driver-class-name: org.postgresql.Driver

---
#Hibernate
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#Actuator configuration
info:
  team:
    dev: Andrian Babii
  version: 1.0.0
  project:
    owner: Andrian Babii

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
