#Data Source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

---
#Hibernate
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
