server:
  ssl:
    key-store: classpath:keystore.jks
    key-password: liberbee
    key-store-type: JKS
    key-alias: liberbee
    key-store-password: liberbee
  port: 8000

#Data Source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

---
#Hibernate
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
